"""add conversations and conversation_messages

Revision ID: 7a8142c4dff7
Revises: 00636dd861b9
Create Date: 2026-08-17 20:08:57.808811

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7a8142c4dff7'
down_revision: str | None = '00636dd861b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate never detects enum value additions - must run outside the
    # migration's transaction (Postgres restriction on ALTER TYPE ... ADD VALUE).
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE learning_event_type ADD VALUE IF NOT EXISTS 'CONVERSATION_CORRECTION'"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario', sa.Enum('RESTAURANT', 'AIRPORT', 'JOB_INTERVIEW', 'SHOPPING', 'CASUAL', 'COLLEGE', 'TRAVEL', name='conversation_scenario'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='conversation_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('LEARNER', 'TUTOR', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.add_column('detected_errors', sa.Column('conversation_message_id', sa.UUID(), nullable=True))
    op.alter_column('detected_errors', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('detected_errors_conversation_message_id_fkey', 'detected_errors', 'conversation_messages', ['conversation_message_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_detected_error_exactly_one_source', 'detected_errors', '(exercise_id IS NOT NULL)::int + (conversation_message_id IS NOT NULL)::int = 1')
    op.add_column('learning_events', sa.Column('conversation_message_id', sa.UUID(), nullable=True))
    op.alter_column('learning_events', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('learning_events_conversation_message_id_fkey', 'learning_events', 'conversation_messages', ['conversation_message_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_learning_event_exactly_one_source', 'learning_events', '(exercise_id IS NOT NULL)::int + (conversation_message_id IS NOT NULL)::int = 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: the CONVERSATION_CORRECTION value added to learning_event_type in
    # upgrade() is NOT removed here - Postgres has no ALTER TYPE ... DROP
    # VALUE. An orphaned enum value is harmless if unused after downgrade.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_learning_event_exactly_one_source', 'learning_events', type_='check')
    op.drop_constraint('learning_events_conversation_message_id_fkey', 'learning_events', type_='foreignkey')
    op.alter_column('learning_events', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('learning_events', 'conversation_message_id')
    op.drop_constraint('ck_detected_error_exactly_one_source', 'detected_errors', type_='check')
    op.drop_constraint('detected_errors_conversation_message_id_fkey', 'detected_errors', type_='foreignkey')
    op.alter_column('detected_errors', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('detected_errors', 'conversation_message_id')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
