"""add leagues quests currency and friendships

Revision ID: c5d5c2fea5a9
Revises: 5e8329ef93bf
Create Date: 2026-08-18 00:50:38.769766

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c5d5c2fea5a9'
down_revision: str | None = '5e8329ef93bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('QUEST_COMPLETED', 'ACHIEVEMENT_UNLOCKED', 'LEAGUE_PROMOTION', name='currency_reason'), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_currency_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'reason', name='uq_currency_transaction_source_reason')
    )
    op.create_index(op.f('ix_currency_transactions_user_id'), 'currency_transactions', ['user_id'], unique=False)
    op.create_table('daily_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quest_date', sa.Date(), nullable=False),
    sa.Column('quest_type', sa.Enum('EARN_XP', 'COMPLETE_LESSON', 'PRACTICE_SESSION', name='quest_type'), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('reward_gems', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_date', 'quest_type', name='uq_daily_quest_user_date_type')
    )
    op.create_index(op.f('ix_daily_quests_user_id'), 'daily_quests', ['user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='friendship_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('requester_id != addressee_id', name='ck_friendship_not_self'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_table('user_leagues',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('SPARK', 'EMBER', 'BLAZE', 'AURORA', 'ZENITH', name='league_tier'), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_leagues')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_daily_quests_user_id'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_index(op.f('ix_currency_transactions_user_id'), table_name='currency_transactions')
    op.drop_table('currency_transactions')
    # ### end Alembic commands ###
