"""add performance indexes on date range columns

Revision ID: cc2e1c228aea
Revises: 45e2477bc564
Create Date: 2026-08-18 20:44:38.766910

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cc2e1c228aea'
down_revision: str | None = '45e2477bc564'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_detected_errors_created_at'), 'detected_errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_events_created_at'), 'learning_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_lesson_attempts_started_at'), 'lesson_attempts', ['started_at'], unique=False)
    op.create_index(op.f('ix_practice_sessions_started_at'), 'practice_sessions', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_sessions_started_at'), table_name='practice_sessions')
    op.drop_index(op.f('ix_lesson_attempts_started_at'), table_name='lesson_attempts')
    op.drop_index(op.f('ix_learning_events_created_at'), table_name='learning_events')
    op.drop_index(op.f('ix_detected_errors_created_at'), table_name='detected_errors')
    # ### end Alembic commands ###
