"""add practice sessions and spaced repetition fields

Revision ID: db238843d38b
Revises: f640acea0ddd
Create Date: 2026-08-17 18:34:26.718894

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db238843d38b'
down_revision: str | None = 'f640acea0ddd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='practice_session_status'), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_table('practice_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_session_id', 'exercise_id', name='uq_practice_question_session_exercise')
    )
    op.create_index(op.f('ix_practice_questions_practice_session_id'), 'practice_questions', ['practice_session_id'], unique=False)
    # server_defaults match the ORM model's Python-side defaults, and protect
    # against NOT NULL failures if this ever runs against an environment
    # where skill_mastery already has rows.
    op.add_column(
        'skill_mastery',
        sa.Column('ease_factor', sa.Float(), nullable=False, server_default='2.5'),
    )
    op.add_column(
        'skill_mastery',
        sa.Column('repetitions', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'skill_mastery',
        sa.Column('interval_days', sa.Integer(), nullable=False, server_default='0'),
    )
    op.create_check_constraint('ck_skill_ease_factor_floor', 'skill_mastery', 'ease_factor >= 1.3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_skill_ease_factor_floor', 'skill_mastery', type_='check')
    op.drop_column('skill_mastery', 'interval_days')
    op.drop_column('skill_mastery', 'repetitions')
    op.drop_column('skill_mastery', 'ease_factor')
    op.drop_index(op.f('ix_practice_questions_practice_session_id'), table_name='practice_questions')
    op.drop_table('practice_questions')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    # ### end Alembic commands ###
