"""add course engine tables

Revision ID: f355827198d0
Revises: b34cb9f9bc58
Create Date: 2026-08-17 15:06:07.780553

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f355827198d0'
down_revision: str | None = 'b34cb9f9bc58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_language_id'), 'courses', ['language_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_skill_course_code')
    )
    op.create_index(op.f('ix_skills_course_id'), 'skills', ['course_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position', name='uq_unit_course_position')
    )
    op.create_index(op.f('ix_units_course_id'), 'units', ['course_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'position', name='uq_lesson_unit_position')
    )
    op.create_index(op.f('ix_lessons_unit_id'), 'lessons', ['unit_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('MULTIPLE_CHOICE', 'FILL_BLANK', 'TRANSLATION', 'WORD_ORDER', 'MATCHING', name='exercise_type'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_exercise_lesson_position')
    )
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_exercises_skill_id'), 'exercises', ['skill_id'], unique=False)
    op.create_table('lesson_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='lesson_attempt_status'), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_attempts_lesson_id'), 'lesson_attempts', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_attempts_user_id'), 'lesson_attempts', ['user_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_attempt_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('submitted_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_attempt_id'], ['lesson_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_attempt_id', 'exercise_id', name='uq_exercise_attempt_per_lesson_attempt')
    )
    op.create_index(op.f('ix_exercise_attempts_lesson_attempt_id'), 'exercise_attempts', ['lesson_attempt_id'], unique=False)
    op.create_table('exercise_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('correct_position', sa.Integer(), nullable=True),
    sa.Column('match_group', sa.String(length=10), nullable=True),
    sa.Column('match_key', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_options_exercise_id'), 'exercise_options', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_options_exercise_id'), table_name='exercise_options')
    op.drop_table('exercise_options')
    op.drop_index(op.f('ix_exercise_attempts_lesson_attempt_id'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_lesson_attempts_user_id'), table_name='lesson_attempts')
    op.drop_index(op.f('ix_lesson_attempts_lesson_id'), table_name='lesson_attempts')
    op.drop_table('lesson_attempts')
    op.drop_index(op.f('ix_exercises_skill_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_lessons_unit_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_units_course_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_skills_course_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_courses_language_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('languages')
    # ### end Alembic commands ###
